// examples/react-grid-minimal/App.tsx
/**
 * Minimal isolated React grid example.
 *
 * The ONLY Jects imports are the grid wrapper subpath and the grid engine:
 *
 *   import { JectsGrid } from '@jects/react/grid';   // <- per-component subpath
 *   import '@jects/grid/style.css';                  // <- engine styles
 *
 * Because `@jects/react/grid` resolves to `dist/grid.js`, which imports only
 * `@jects/grid` (plus the shared factory), a bundler building this app never
 * touches `@jects/gantt`, `@jects/scheduler`, or any other sibling engine — they
 * are not dependencies of this package at all. That is the whole point of the
 * per-component subpath exports: install one component, ship one component.
 */
import { JectsGrid } from '@jects/react/grid';
import '@jects/grid/style.css';

interface Person {
  id: number;
  name: string;
  role: string;
}

const data: Person[] = [
  { id: 1, name: 'Ada Lovelace', role: 'Engineer' },
  { id: 2, name: 'Grace Hopper', role: 'Admiral' },
  { id: 3, name: 'Katherine Johnson', role: 'Mathematician' },
];

export function App(): JSX.Element {
  return (
    <main style={{ padding: 24 }}>
      <h1>Isolated @jects/react/grid</h1>
      <JectsGrid
        data={data}
        columns={[
          { field: 'name', header: 'Name' },
          { field: 'role', header: 'Role' },
        ]}
        style={{ height: 320 }}
        onSelectionChange={(payload) => {
          // The grid's typed events bridge through to React `on<Event>` props.
          console.log('selection changed', payload);
        }}
      />
    </main>
  );
}

// examples/angular-grid-minimal/app.component.ts
/**
 * Minimal Angular standalone component that renders a Jects grid and nothing else.
 *
 * The ONLY Jects imports are the grid subpath of the wrapper and the grid engine:
 *
 *     import { JectsGrid } from '@jects/angular/grid';   // -> dist/grid.js
 *     import type { GridOptions } from '@jects/grid';
 *
 * Because `@jects/angular/grid` resolves to `dist/grid.js` — whose only `@jects/*`
 * import is `@jects/grid` — a bundler building this app never resolves any sibling
 * engine (`@jects/gantt`, `@jects/scheduler`, `@jects/widgets`, …). That is the whole
 * point of the per-component subpath exports: install/bundle one component in isolation.
 *
 * Compare with `import { JectsGrid } from '@jects/angular'` (the root entry), which
 * re-exports every wrapper and would drag every engine into resolution.
 */
import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { JectsGrid } from '@jects/angular/grid';
import type { GridOptions } from '@jects/grid';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [JectsGrid],
  changeDetection: ChangeDetectionStrategy.OnPush,
  // `[config]` is the wrapper's signal input; `(jectsEvent)` is its typed event output.
  template: `
    <h1>@jects/angular/grid — isolated install</h1>
    <jects-grid
      [config]="gridConfig()"
      [events]="['selectionChange']"
      (jectsEvent)="onGridEvent($event)"
    ></jects-grid>
  `,
})
export class AppComponent {
  readonly gridConfig = signal<GridOptions>({
    data: [
      { id: 1, name: 'Ada Lovelace', role: 'Engineer' },
      { id: 2, name: 'Grace Hopper', role: 'Admiral' },
    ],
    columns: [
      { field: 'name', header: 'Name' },
      { field: 'role', header: 'Role' },
    ],
  });

  onGridEvent(event: { type: string; payload: unknown }): void {
    // The single typed output: narrow on `event.type` for a typed `event.payload`.
    // eslint-disable-next-line no-console
    console.log('grid event', event.type, event.payload);
  }
}
