// examples/react-gantt-minimal/App.tsx
/**
 * Minimal isolated React gantt example.
 *
 * The ONLY Jects imports are the gantt wrapper subpath and the gantt engine:
 *
 *   import { JectsGantt } from '@jects/react/gantt'; // <- per-component subpath
 *   import '@jects/gantt/style.css';                 // <- engine styles
 *
 * Because `@jects/react/gantt` resolves to `dist/gantt.js`, which imports only
 * `@jects/gantt` (plus the shared factory), a bundler building this app never
 * touches `@jects/grid`, `@jects/scheduler`, or any other sibling engine — they
 * are not dependencies of this package at all. That is the whole point of the
 * per-component subpath exports: install one component, ship one component.
 */
import { JectsGantt } from '@jects/react/gantt';
import '@jects/gantt/style.css';

// Epoch-ms helper so the tiny task list reads as real dates.
const day = (iso: string): number => new Date(iso).getTime();

interface TaskExtra {
  owner: string;
}

const tasks = [
  {
    id: 1,
    name: 'Design',
    start: day('2026-07-01'),
    end: day('2026-07-04'),
    percentDone: 1,
    data: { owner: 'Ada Lovelace' },
  },
  {
    id: 2,
    name: 'Build',
    start: day('2026-07-04'),
    end: day('2026-07-10'),
    percentDone: 0.4,
    data: { owner: 'Grace Hopper' },
  },
  {
    id: 3,
    name: 'Ship',
    start: day('2026-07-10'),
    milestone: true,
    data: { owner: 'Katherine Johnson' },
  },
];

const dependencies = [
  { id: 1, fromId: 1, toId: 2, type: 'FS' as const },
  { id: 2, fromId: 2, toId: 3, type: 'FS' as const },
];

export function App(): JSX.Element {
  return (
    <main style={{ padding: 24 }}>
      <h1>Isolated @jects/react/gantt</h1>
      <JectsGantt
        tasks={tasks}
        dependencies={dependencies}
        columns={[
          { field: 'name', header: 'Task' },
          { field: 'percentDone', header: '% Done' },
        ]}
        style={{ height: 320 }}
        onTaskClick={(payload) => {
          // The gantt's typed events bridge through to React `on<Event>` props.
          console.log('task clicked', payload);
        }}
      />
    </main>
  );
}

// examples/angular-gantt-minimal/app.component.ts
/**
 * Minimal Angular standalone component that renders a Jects gantt and nothing else.
 *
 * The ONLY Jects imports are the gantt subpath of the wrapper and the gantt engine:
 *
 *     import { JectsGantt } from '@jects/angular/gantt'; // -> dist/gantt.js
 *     import type { GanttOptions } from '@jects/gantt';
 *     import '@jects/gantt/style.css';
 *
 * Because `@jects/angular/gantt` resolves to `dist/gantt.js` — whose only `@jects/*`
 * import is `@jects/gantt` — a bundler building this app never resolves any sibling
 * engine (`@jects/grid`, `@jects/scheduler`, `@jects/widgets`, …). That is the whole
 * point of the per-component subpath exports: install/bundle one component in isolation.
 *
 * Compare with `import { JectsGantt } from '@jects/angular'` (the root entry), which
 * re-exports every wrapper and would drag every engine into resolution.
 */
import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { JectsGantt } from '@jects/angular/gantt';
import type { GanttOptions } from '@jects/gantt';
import '@jects/gantt/style.css';

const DAY = 24 * 60 * 60 * 1000;
const PROJECT_START = Date.UTC(2026, 0, 5); // Mon 2026-01-05

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [JectsGantt],
  changeDetection: ChangeDetectionStrategy.OnPush,
  // `[config]` is the wrapper's signal input; `(jectsEvent)` is its typed event output.
  template: `
    <h1>@jects/angular/gantt — isolated install</h1>
    <jects-gantt
      [config]="ganttConfig()"
      [events]="['taskClick']"
      (jectsEvent)="onGanttEvent($event)"
    ></jects-gantt>
  `,
})
export class AppComponent {
  readonly ganttConfig = signal<GanttOptions>({
    projectStart: PROJECT_START,
    tasks: [
      { id: 1, name: 'Design', start: PROJECT_START, duration: 2 * DAY, percentDone: 1 },
      { id: 2, name: 'Build', start: PROJECT_START + 2 * DAY, duration: 3 * DAY, percentDone: 0.5 },
      { id: 3, name: 'Ship', start: PROJECT_START + 5 * DAY, duration: 0, milestone: true },
    ],
    dependencies: [
      { id: 1, fromId: 1, toId: 2, type: 'FS' },
      { id: 2, fromId: 2, toId: 3, type: 'FS' },
    ],
    columns: [
      { field: 'name', header: 'Task' },
      { field: 'duration', header: 'Duration' },
    ],
  });

  onGanttEvent(event: { type: string; payload: unknown }): void {
    // The single typed output: narrow on `event.type` for a typed `event.payload`.
    // eslint-disable-next-line no-console
    console.log('gantt event', event.type, event.payload);
  }
}
