// examples/angular-scheduler-minimal/app.component.ts
/**
 * Minimal Angular standalone component that renders a Jects scheduler and nothing else.
 *
 * The ONLY Jects imports are the scheduler subpath of the wrapper and the scheduler engine:
 *
 *     import { JectsScheduler } from '@jects/angular/scheduler';   // -> dist/scheduler.js
 *     import type { SchedulerConfig } from '@jects/scheduler';
 *
 * Because `@jects/angular/scheduler` resolves to `dist/scheduler.js` — whose only `@jects/*`
 * import is `@jects/scheduler` — a bundler building this app never resolves any sibling
 * engine (`@jects/grid`, `@jects/gantt`, `@jects/widgets`, …). That is the whole
 * point of the per-component subpath exports: install/bundle one component in isolation.
 *
 * Compare with `import { JectsScheduler } from '@jects/angular'` (the root entry), which
 * re-exports every wrapper and would drag every engine into resolution.
 */
import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { JectsScheduler } from '@jects/angular/scheduler';
import type { SchedulerConfig } from '@jects/scheduler';
// Engine CSS for the scheduler (resolves via the package `exports` map to dist/style.css).
import '@jects/scheduler/style.css';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [JectsScheduler],
  changeDetection: ChangeDetectionStrategy.OnPush,
  // `[config]` is the wrapper's signal input; `(jectsEvent)` is its typed event output.
  template: `
    <h1>@jects/angular/scheduler — isolated install</h1>
    <jects-scheduler
      [config]="schedulerConfig()"
      [events]="['eventClick']"
      (jectsEvent)="onSchedulerEvent($event)"
    ></jects-scheduler>
  `,
})
export class AppComponent {
  // Tiny but valid config: two resource lanes and two events on them. `startDate`
  // / `endDate` are epoch ms (UTC); `range` bounds the visible timeline span.
  readonly schedulerConfig = signal<SchedulerConfig>({
    resources: [
      { id: 1, name: 'Ada Lovelace' },
      { id: 2, name: 'Grace Hopper' },
    ],
    events: [
      {
        id: 1,
        resourceId: 1,
        name: 'Design review',
        startDate: Date.UTC(2026, 5, 25, 9, 0),
        endDate: Date.UTC(2026, 5, 25, 11, 0),
      },
      {
        id: 2,
        resourceId: 2,
        name: 'Deploy',
        startDate: Date.UTC(2026, 5, 25, 13, 0),
        endDate: Date.UTC(2026, 5, 25, 15, 0),
      },
    ],
  });

  onSchedulerEvent(event: { type: string; payload: unknown }): void {
    // The single typed output: narrow on `event.type` for a typed `event.payload`.
    // eslint-disable-next-line no-console
    console.log('scheduler event', event.type, event.payload);
  }
}

// examples/react-scheduler-minimal/App.tsx
/**
 * Minimal isolated React scheduler example.
 *
 * The ONLY Jects imports are the scheduler wrapper subpath and the scheduler engine:
 *
 *   import { JectsScheduler } from '@jects/react/scheduler';   // <- per-component subpath
 *   import '@jects/scheduler/style.css';                       // <- engine styles
 *
 * Because `@jects/react/scheduler` resolves to `dist/scheduler.js`, which imports
 * only `@jects/scheduler` (plus the shared factory), a bundler building this app
 * never touches `@jects/grid`, `@jects/gantt`, or any other sibling engine — they
 * are not dependencies of this package at all. That is the whole point of the
 * per-component subpath exports: install one component, ship one component.
 */
import { JectsScheduler } from '@jects/react/scheduler';
import '@jects/scheduler/style.css';

// A tiny, valid scheduler config: two resource lanes and three events placed on
// them. Times are epoch ms (TimeMs); `endDate` is exclusive.
const DAY = '2026-06-25T00:00:00Z';
const at = (hour: number): number => new Date(DAY).getTime() + hour * 60 * 60 * 1000;

const resources = [
  { id: 1, name: 'Room A' },
  { id: 2, name: 'Room B' },
];

const events = [
  { id: 1, resourceId: 1, name: 'Standup', startDate: at(9), endDate: at(10) },
  { id: 2, resourceId: 1, name: 'Design review', startDate: at(11), endDate: at(13) },
  { id: 3, resourceId: 2, name: 'Client call', startDate: at(10), endDate: at(11) },
];

export function App(): JSX.Element {
  return (
    <main style={{ padding: 24 }}>
      <h1>Isolated @jects/react/scheduler</h1>
      <JectsScheduler
        resources={resources}
        events={events}
        style={{ height: 320 }}
        onEventClick={(payload) => {
          // The scheduler's typed events bridge through to React `on<Event>` props.
          console.log('event clicked', payload);
        }}
      />
    </main>
  );
}
